CREATE DATABASE CASTELLO_EXTENSAOVS
    DEFAULT CHARACTER SET = 'utf8mb4';

USE CASTELLO_EXTENSAOVS;

-- VISUALIZAR TABELAS DO MEU BD
SHOW TABLES;

-- VISUALIZAR TODOS OS BD
SHOW SCHEMAS;

-- CRIAR TABELAS
CREATE TABLE IF NOT EXISTS ALUNOS (
    ID_CLIENTE BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    TELEFONE CHAR(15),
    DATA_NASCIMENTO DATETIME,
    STATUS ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);